Add rstcheck
tsuyoshicho/vim-efm-langserver-settings pull request #102
Opened 2020-11-23 23:05 UTC by polyzen

For some reason the error messages for code blocks have the `($language)` truncated.

Output at command-line:
`bad_code.rst:9: (ERROR/3) (python) unexpected EOF while parsing`

Output from `:LspDocumentDiagnostics`:
`bad_code.rst|9 col 1| Error:unexpected EOF while parsing`

2020-11-23 23:10 UTC, tsuyoshicho commented
Thanks, I check it.

2020-11-24 01:27 UTC, tsuyoshicho requested changes
Add config info.

2020-11-24 01:27 UTC, tsuyoshicho commented on config/efm-langserver/config.yaml
> +
```suggestion
    root-markers:
      - .rstcheck.cfg

```

add root marker

2020-11-24 01:27 UTC, tsuyoshicho commented on README.md
> +| [rstcheck](https://github.com/myint/rstcheck)                            | rst                                                                          | lint               | pip                  |
```suggestion
| [rstcheck](https://github.com/myint/rstcheck)                            | rst                                                                          | lint               | pip                  | not need config / user config affected   | `.rstcheck.cfg` in the project root.                                         |
```

note for config.
(and cell width fix...)

2020-11-24 02:19 UTC, tsuyoshicho requested changes

2020-11-24 02:19 UTC, tsuyoshicho commented on config/efm-langserver/config.yaml
> +      - '%f:%l: (%tEVERE/%r) %m'
```suggestion
      - '%f:%l: (%tNFO/%*[A-Z0-9]) %m'
      - '%f:%l: (%tARNING/%*[A-Z0-9]) %m'
      - '%f:%l: (%tRROR/%*[A-Z0-9]) %m'
      - '%f:%l: (%tEVERE/%*[A-Z0-9]) %m'
```

```
	%r		matches the "rest" of a single-line file message %O/P/Q
	%*{conv}	any scanf non-assignable conversion
```

message `<file>:<line>: (ERROR/3) (python) foobar...` and `(%tRROR/%r)` matcher, match `(ERROR/3) (python)` as many as possible matching result.

2020-11-24 06:13 UTC, merged

2020-11-24 06:13 UTC, tsuyoshicho commented
Thanks for your PR.

I fixed and updated it here and merged it.

2020-11-24 06:15 UTC, polyzen commented
Thank you!